### ISSUE TITLE
 android_hardware_samsung fails to download for Lineage 20, as there is no lineage-20.0 branch

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [samsungexynos7420/local_manifests#1]
For android_hardware_samsung, the universal7420.xml says to get the lineage-20.0 branch of the repository, however android_hardware_samsung does not have a branch for 20, causing the download to fail.

**Comment by fakemanoan** [comment]
the samsungexynos7420 hardware_samsung repository doesnt have a lineage-20 branch as of yet. Maybe in the future it will to better support other variants, however using the LineageOS one is completely fine,

Fixed in https://github.com/samsungexynos7420/local_manifests/commit/cc455465d409735fe6a855b7042140b782557113
